apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-hub.fullname" . }}-serilog-config
  labels:
{{ include "notification-hub.labels" . | indent 4 }}
binaryData:
  serilog.config: {{ .Values.serilogConfig }}

