{{- if .Values.overrideTemplateSeedData }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "notification-hub.fullname" . }}-templateseeddata
  labels:
{{ include "notification-hub.labels" . | indent 4 }}
data:
{{ (.Files.Glob  "TemplateSeedData/**.json").AsConfig | indent 2 }}
{{- end }}

