{{- if .Values.azure.aad.enabled }}
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ .Values.azure.aad.identityname }}
  {{- if .Values.azure.aad.namespace }}
  namespace: {{ .Values.azure.aad.namespace }}
  {{- end }}
spec:
  type: {{ .Values.azure.aad.identitytype }}
  resourceID: {{ .Values.azure.aad.identityresourceid }}
  clientID: {{ .Values.azure.aad.identityclientid }}
{{- end }}